version: '3.4'

services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile
    depends_on:
      - catalog.db
  catalog.db:
    image: "mcr.microsoft.com/mssql/server"
    command: /bin/bash /entrypoint.sh
    environment:
        SA_PASSWORD: "Catalog_123"
        ACCEPT_EULA: "Y"
    volumes:
      - ./src/Services/Catalog/Catalog.DB/entrypoint.sh:/entrypoint.sh
      - ./src/Services/Catalog/Catalog.DB/eShopOnContainersCatalog.sh:/eShopOnContainersCatalog.sh
      - ./src/Services/Catalog/Catalog.DB/eShopOnContainersCatalog.sql:/eShopOnContainersCatalog.sql
    