version: '3.4'

services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile
    depends_on:
      - catalog.db
      - bus
  catalog.db:
    container_name: ${DOCKER_REGISTRY-}Catalog.DB
    image: "mcr.microsoft.com/mssql/server"
    command: /bin/bash /entrypoint.sh
    environment:
        SA_PASSWORD: "Catalog_123"
        ACCEPT_EULA: "Y"
    ports:
      - 11433:1433
    volumes:
      - ./src/Services/Catalog/Catalog.DB/entrypoint.sh:/entrypoint.sh
      - ./src/Services/Catalog/Catalog.DB/eShopOnContainersCatalog.sh:/eShopOnContainersCatalog.sh
      - ./src/Services/Catalog/Catalog.DB/eShopOnContainersCatalog.sql:/eShopOnContainersCatalog.sql
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: src/Services/Basket/Basket.API/Dockerfile
    depends_on:
      - basket.db
      - catalog.api
      - bus
  basket.db:
    container_name: ${DOCKER_REGISTRY-}Basket.DB
    image: redis:alpine    

  webspa:
    image: ${DOCKER_REGISTRY-}webspa
    build:
      context: .
      dockerfile: src/Web/WebSPA/Dockerfile
    depends_on:
      - basket.api
      - catalog.api
      - ordering.api
  cdn:
    image: halverneus/static-file-server
    ports:
      - 8080:8080
    environment:
      - FOLDER=/content
    volumes:
      - ./src/Web/CDN:/content

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: src/Services/Ordering/Ordering.API/Dockerfile

  ordering.db:
    container_name: ${DOCKER_REGISTRY-}Ordering.DB
    image: redis:alpine    

  bus:
    container_name: ${DOCKER_REGISTRY-}BUS
    image: rabbitmq:3-management-alpine
    